language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "chumdanei-github"
    token:
      secure: "scVge9sckXFD5Btqrc1Cp/KLyk1F6cTVB50M5P8xpJ5gwCYyg3PyL1zz3F0lN6GqqqKFKPpLYUoz3LK/MfM0IOnQgYc6zQHyCmnDjH6a3lud7akYDsJSjlgEaRdGxPshzfNPiU4O1MFWJSSFvxrDIw72w/KmPzg+acu/ObiCdNwgWPWKK3MDAKHjtNZWy1FMTnspwIl6Bzx+vPmkeuDnv3qrDtQc/jAxOkmKMrDB4ejeoi5P3q2CEUOQ4bCSu/8YVuZleE2EZLRT/smEtoKY0ofbzpUmyBtSY2ALnbpxdyQ7gt7SOO7Ty2lBFK49M0lBD1Un6snfFA6PBoJbZtijGbDmvLpI8HSJ37vE5eIETmn1RWrsZmNTnBp4rzemw5RtZ+WI3/jWuDdFULv++eJn/m2vgjzmekKrRy1Q1jnIT8rNRXzcZ8AEKSK8JqdhTBqSbOtN4NZhXSf63aaa9DoOzCVWcE7hv1c6DADraAzyZvk5vVH2sxeXlM+2d52Z7T4GrU9GDANuewP50XEUHdDNDtZ7W4ycaqQO1oriT5PJx1AjPTK9AkN0n98jUIcoSxUv5uRENzRmID/m1Uf1j5qCpLjQi86E3XpNSJdEwf6H0PdgS+MIlsIIC6QTMkVwX+HarKvFmqcurl9g4R3JmJaZSS7LK4YAD5mysnSaY2AWAbY="
jdk:
  - oraclejdk8 -X
  
script:
  - jdk_switcher use oraclejdk8
  - sonar-scanner -X
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
notification:
  email: false