language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "kitswdevteam-github"
    token:
      secure: "Meg7WQi7R+Hx5AScRFL2g0j7WITFqn2LywOYImYNCuBZSdfbmPM1nQlEljTfBRdyrww7O5JhZi5cRkdxHqFRJH++OScgly5QIehVzbuRVAl22ZhbBkmfRSV2/QGlLrniDZW2c6N0hoRi5Jvixlt9pKYPsCkMw900o4NkEtRlvuNpo/pvg4rK8RS+3toEo8jiUMHEVWJcheHF7jX9993QcVURs8NJ+2hVH5cdyW3DDKEjQ/wQ4r3eizIZY7dI/7rkPr/k3HZICLX0E6MmHhsmkrKcG5KcflXzCnbojGgRIOmPvjviYt6MIo6MtPNKp75/LVJej18WjKZH1dQSjT0+KNPwh+MBFZZIWEdwI6jIgJuj6aZ+Ex/SC/0MVX/Ej6e07mfUHe6NJ34kXl3Y/3K9nFC8IiAXPK1w3zw0I2oPo+mUD7yodQKMTW9Zh9glePsxj/DEImgTIRdoDVcNxsHKLhjRBPp4e0Of7eCZC/3BwaPnvGIO2JgVRagZevxJ4MySUntf31z6rHheMwCmOQ5NgA7+qd9hiFABkmJ6DI/9bJf1Tx2RI2dXtETr9VK6Vz0ziWua9iTf6OUJWnQm6hBSWU4KWgNNLxR6o30DyNpgSYcDlJ8xeWPr6hQEWXW74O07ayyqJoQg26EnW57HWyE9AXpH7Ef/1gHDPc/EBi/JHlY="
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'