language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "kitswdevteam-github"
    token:
      secure: "X2Y8GIzVThepKO60CAp6f8Gdq3xWlFdVQ6iB5bbvQZ94PhqGHrlAlRBfci4ISDMOaSkeC+8Soh1xk5dQ7zEURJcU0qE/PF24s/ydoJ4E5WouqnHCsFr7HzPO4d8tDwIZn3spIdcCP++zY5Igsi8lFq2NJvDsrYR/C06kPncZz6psm6HF0mZKV7Gv6wUqR6+P044qnmFFLbdkNfbponE6xqvPLcClyPwvpGKZqWJhCknzWq0gsMwI8pDZjChVTAtYm7MdpElE/uzUtt34O3Pu3fqzNEMIKuqmGdPSERTp3Ju9ERoniLpl29RgqgfccJ/TL2AQXXoxooBFpNUSofJOh7o0tJzcQCUhM4DB+AFjzwq1nUPsXpiNPInfQpkFxZ+AMgZEEFzaSaEXibd1g/h7abLPmNbKt4BldOmFTpIzVl95LNte4ZMuIYLaym9jffdkJvhxN0qIJDIPg1j9wpgZsyvScjQmHSVpgjcWXwIzBbGEOEYM2GWBgrKFRT/KliiMbQYemVKNGng4eUBQTAzD2MpQBKXe3nWCTWxyX6aNFM849ixVxWZ6RP0nhZ0iwft8+pgErikyTto8KRvHkhClaNqg7WIMS5hxIwlCE+EMnHr9Yo680osIKaU5/R1JzApTlxAqGxqk/a3om8CVfb+X8SeWwKWlJyzgZM7OAmKNVk8="
jdk:
  - oraclejdk8 
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
notification:
  email: false